name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            target: aarch64-apple-darwin
          - os: macos-13
            target: x86_64-apple-darwin
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust (stable) + target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build (release)
        run: cargo build --locked --release --target ${{ matrix.target }}

      - name: (Optional) Strip binary
        shell: bash
        run: |
          BIN="tusk"
          TGT="${{ matrix.target }}"
          BIN_PATH="target/${TGT}/release/${BIN}"
          if [[ "$TGT" == *linux* ]]; then strip "$BIN_PATH" || true; fi
          if [[ "$TGT" == *apple-darwin ]]; then strip -x "$BIN_PATH" || true; fi

      - name: Package
        shell: bash
        run: |
          set -eux
          BIN="tusk"  # your binary name
          TGT="${{ matrix.target }}"
          VER="${GITHUB_REF_NAME#v}"
          PKG_DIR="${BIN}-${VER}-${TGT}"
          mkdir -p "$PKG_DIR"
          cp "target/${TGT}/release/${BIN}" "$PKG_DIR/"
          cp LICENSE "$PKG_DIR/"
          cp README.md "$PKG_DIR/"
          zip -r "${PKG_DIR}.zip" "$PKG_DIR"
          echo "ASSET=${PKG_DIR}.zip" >> $GITHUB_ENV

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}